import pygame 
screen = pygame.display.init()
size = (800,800)
screen = pygame.display.set_mode(size)
screen.fill(pygame.Color("white"))
pygame.draw.circle(screen,'grey',(400,50),60) 
pygame.display.flip() 
pygame.time.delay(10) 
pygame.draw.circle(screen,'white',(400,50),55) 
pygame.display.flip() 
pygame.time.delay(10)
pygame.draw.circle(screen,'grey',(400,160),85) 
pygame.display.flip() 
pygame.time.delay(10)
pygame.draw.circle(screen,'white',(400,160),80) 
pygame.display.flip() 
pygame.time.delay(10) 
pygame.draw.circle(screen,'grey',(400,250),105) 
pygame.display.flip() 
pygame.time.delay(10)
pygame.draw.circle(screen,'white',(400,250),100) 
pygame.display.flip() 
pygame.time.delay(1000)
